version: '3'

services:
  api-vasly:
    image: bitnami/postgresql:latest
    ports:
      - 5434:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api-vasnly
      - POSTGRESQL_REPLICATION_USE_PASSFILE=false
